name: duplikasi_bima
description: Duplikasi Bima+ (Percobaan ke-2)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/icons/buy.svg
    - assets/icons/cowboy_hat_face.svg
    - assets/icons/globe.svg
    - assets/icons/greater_than.svg
    - assets/icons/grid.svg
    - assets/icons/headset.svg
    - assets/icons/layers.svg
    - assets/icons/loading_bar.svg
    - assets/icons/market_stall.svg
    - assets/icons/media_player.svg
    - assets/icons/notification.svg
    - assets/icons/person.svg
    - assets/icons/phone.svg
    - assets/icons/rocket.svg
    - assets/icons/search.svg
    - assets/icons/star_circle.svg
    - assets/icons/discount_circle.svg
    - assets/icons/voucher.svg
    - assets/icons/shield_user.svg
    - assets/icons/money_bag.svg

    - assets/images/icon_launcher_rounded.png
    - assets/images/header_background.jpg
    - assets/images/splash_screen.jpg

    - assets/images/promo_pilihan/shopee_pay.png
    - assets/images/promo_pilihan/happy_flex.png
    - assets/images/promo_pilihan/promo_pegi_pegi.png
    - assets/images/promo_pilihan/panjat_kuota.png
    - assets/images/promo_pilihan/h3ro.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
